# Generated by Django 3.1.5 on 2021-01-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('cover_image_url', models.CharField(max_length=300)),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('CO', 'Comedy'), ('CR', 'Crime'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('HI', 'Historical'), ('HO', 'Horror'), ('MY', 'Mystery'), ('PO', 'Political'), ('RO', 'Romance'), ('TH', 'Thiller'), ('WE', 'Western')], default='AC', max_length=2)),
            ],
        ),
    ]
